### Listar posts
GET http://localhost:8000/api/posts

### Listar posts com paginação
GET http://localhost:8000/api/posts?page=2

### Listar posts com paginação e filtro
GET http://localhost:8000/api/posts/fugit-autem-corrupti-magnam-aspernatur-voluptatem-accusantium-autem

### Ver post específico
GET http://localhost:8000/api/posts?category=saude
Accept: application/json

### Listar categorias
GET http://localhost:8000/api/categories

### Listar tags
GET http://localhost:8000/api/tags

### Listar anúncios de topo
GET http://localhost:8000/api/ads?position=home_top

### Listar anúncios
GET http://localhost:8000/api/ads

### Listar posições de anúncios
GET http://localhost:8000/api/ads/positions

### Enviar contato type is advertise or contact
POST http://localhost:8000/api/contacts
Content-Type: application/json

{
  "name": "Tiago",
  "email": "t@t.com",
  "phone": "123456789",
  "type": "advertise",
  "company": "Teste Ltda",
  "message": "Olá, quero anunciar..."
}
